In [1]:
import numpy as np

In [2]:
a = [1,2,3]
b = [1,2,3]
c = a+b
print(c)

[1, 2, 3, 1, 2, 3]


In [3]:
a = np.array([1,2,3])
b = np.array([1,2,3])
c = a+b
print(c)

[2 4 6]


In [5]:
a = np.array([1,2,3])
b = np.array([1,2,3])

add = a+b
mul = a*b
sub = a-b
div = a/b

print(add)
print(mul)
print(sub)
print(div)

[2 4 6]
[1 4 9]
[0 0 0]
[1. 1. 1.]


In [11]:
# https://numpy.org/doc/1.24/reference/generated/numpy.ndarray.max.html

a = [1,2,3,4,5]
b = np.array([1,2,3,4,5])
c = np.max([1,2,3,4,5])

print(np.max(a))
print(np.max(b))
print(c)

5
5
5


In [26]:
a = [
    [1, 2, 3, 4, 5], 
    [5, 6, 7, 8, 5],
    [5, 6, 7, 8, 5]
]

b = np.array(a)

print(b.shape)

(3, 5)


In [92]:
a = np.array([1,2,3])
b = np.array([4,5,6])   
c = np.concatenate((a,b))

print(c)

[1 2 3 4 5 6]


In [99]:
a = [1,2,3,4,5]
b = [1,2,3,4,5]
c = [ [1,2,3], [4,5,6]]

n1 = np.transpose(c)
n2 = np.min(c)
n3 = np.max(c)
n4 = np.sqrt(c)
n5 = np.square(c)
n6 = np.transpose(c)

print("transpose: ", n1)
print("min: ", n2)
print("max: ", n3)
print("sqrt: ", n4)
print("square: ", n5)
print("transpose: ", n6)

transpose:  [[1 4]
 [2 5]
 [3 6]]
min:  1
max:  6
sqrt:  [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]
square:  [[ 1  4  9]
 [16 25 36]]
transpose:  [[1 4]
 [2 5]
 [3 6]]
